name: ADAM-CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  r-cmd-check:
    name: R CMD check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::BiocManager
            any::rcmdcheck

      - name: R CMD check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: false
          error-on: '"warning"'

  bioccheck:
    name: BiocCheck (ubuntu)
    runs-on: ubuntu-latest
    needs: r-cmd-check
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::BiocManager
            bioc::BiocCheck
            local::.

      - name: BiocCheck
        shell: Rscript {0}
        run: |
          BiocCheck::BiocCheck(
            ".",
            `no-check-bioc-help` = TRUE
          )
